<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEI57hwq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEI57hwq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEI57hwq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEI57hwq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEI57hwq\App_KernelDevDebugContainer([
    'container.build_hash' => 'EI57hwq',
    'container.build_id' => '679b7c26',
    'container.build_time' => 1670006059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEI57hwq');
