<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcATgfF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcATgfF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFcATgfF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFcATgfF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFcATgfF\App_KernelDevDebugContainer([
    'container.build_hash' => 'FcATgfF',
    'container.build_id' => 'bdaf0909',
    'container.build_time' => 1669716217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcATgfF');
