<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1rEn0XB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1rEn0XB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1rEn0XB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1rEn0XB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1rEn0XB\App_KernelDevDebugContainer([
    'container.build_hash' => '1rEn0XB',
    'container.build_id' => 'f3ee46ec',
    'container.build_time' => 1669734204,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1rEn0XB');
